name: Code Style
description: Check code style
runs:
  using: "composite"
  steps:
    - name: Black
      shell: bash
      run: black --check ./

    - name: Mypy
      shell: bash
      run: mypy ./

    - name: Flake8
      shell: bash
      run: flake8 ./
