name: On Push
on: [push]
jobs:
  on_push:
    name: Fast Checker
    runs-on: ubuntu-latest
    steps:
      - name: Run checkout
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: ./.github/actions/environment/python

      - name: Check code style
        uses: ./.github/actions/code-style
