name: Continuous Integration
on: [push]
jobs:
  On_Push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pipenv
          pipenv sync --dev

      - name: Black
        run: black --check ./

      - name: Flake8
        run: flake8 ./
